Add section about adyen notification system
mirumee/saleor-docs pull request #188
Opened 2020-10-16 13:29 UTC by korycins

2020-10-16 14:06 UTC, patrys commented
Task linked: [SALEOR-1249 Add paragraph about enabling the Adyen's notifications](https://app.clickup.com/t/2549495/SALEOR-1249)

2020-10-16 14:29 UTC, patrys commented on docs/dashboard/configuration/plugins.md
> +Adyen uses a notification system that can be used to update the payment information on the Saleor side.  Enabling the notification requires some additional steps on the Adyen's customer area panel si
Can't tell if this is required for Saleor to work or optional. Can we provide step-by-step instructions? Even if it's as simple as "step 1: follow this Adyen doc, step 2: use this value as the callback URL, step 3: here's how to verify that it works"?

2020-10-16 14:31 UTC, patrys commented on docs/dashboard/configuration/plugins.md
> +To protect your notification endpoints make sure that you enabled the HMAC signature and basic authentication [Adyen docs about security]([https://docs.adyen.com/development-resources/webhooks/best-p
I think this should be part of the step-by-step instructions above: once you verify that Adyen works, enable payload signing and check again.

2020-10-21 09:52 UTC, maarcingebala approved these changes

2020-10-21 10:50 UTC, karolkielecki commented on docs/dashboard/configuration/plugins.md
> +3. To test your configuration check the [the Adyen docs about testing the configuration.](https://docs.adyen.com/development-resources/webhooks#test-your-notifications-server)
```suggestion
3. To test your configuration check [the Adyen docs about testing the configuration.](https://docs.adyen.com/development-resources/webhooks#test-your-notifications-server)
```

2020-10-21 10:58 UTC, karolkielecki requested changes
Line 87 should be updated

2020-10-27 09:29 UTC, karolkielecki approved these changes

2020-10-29 10:50 UTC, korycins commented
I've updated the docs and screenshot after we added `Enable native 3d secure` and dropped the origin field.

2020-10-29 10:53 UTC, patrys commented on docs/dashboard/configuration/plugins.md
> +- **Enable native 3d secure:** Saleor uses 3D Secure redirect authentication by default. If you want to use native 3D Secure authentication, enable this option. For more details see Adyen documentati
It's either "3-D Secure" (the official name) or "3D Secure". Please use the proper name here and in the actual UI.

2020-10-29 10:55 UTC, patrys commented on docs/dashboard/configuration/plugins.md
> +    * copy HMAC key and paste it to Saleor field **HMAC secret key**. [(See Saleor configuration fields.)](#enabling-the-adyen-integration)
```suggestion
    * Copy the HMAC key into the Saleor's **HMAC secret key** field. [(See Saleor configuration fields.)](#enabling-the-adyen-integration)
```

2020-10-29 10:56 UTC, patrys commented on docs/dashboard/configuration/plugins.md
> +    * for `URL` use `https://<your-backend-url>/plugins/mirumee.payments.adyen/webhooks/`.
Start with a capital letter when ending the sentence with a dot.

2020-11-02 15:41 UTC, patrys commented on docs/dashboard/configuration/plugins.md
> +- **Enable native 3D secure:** Saleor uses 3D Secure redirect authentication by default. If you want to use native 3D Secure authentication, enable this option. For more details see Adyen documentati
```suggestion
- **Enable native 3D Secure:** Saleor uses 3D Secure redirect authentication by default. If you want to use native 3D Secure authentication, enable this option. For more details see Adyen documentation: [native 3D Secure 2](https://docs.adyen.com/checkout/3d-secure/native-3ds2), [redirect 3D Secure 1 and 2](https://docs.adyen.com/checkout/3d-secure/redirect-3ds2-3ds1)
```

2020-11-03 08:27 UTC, maarcingebala approved these changes

2020-11-03 13:20 UTC, karolkielecki approved these changes

2020-11-04 09:28 UTC, merged