communication (notification) interface
mirumee/saleor-docs pull request #246
Opened 2021-03-19 15:41 UTC by korycins

2021-04-09 05:37 UTC, korycins commented on docs/developer/available-plugins/user-emails.mdx
> +[WebhookEventTypeEnum](developer/api-reference/enums/webhook-event-type-enum.mdx) contain all availabe events.
It is a link to Webhook events. Which are not really related to the notification events.

2021-04-09 05:45 UTC, korycins commented on docs/developer/available-plugins/user-emails.mdx
> +- **latin** (boolean) - ???
It is a value passed to i18naddress library. 
https://github.com/mirumee/google-i18n-address#address-latinization

2021-04-09 05:45 UTC, korycins commented on docs/developer/available-plugins/user-emails.mdx
> +- compare_operator (string) - Available operators: `==`,`!=`,`<`,`<=`,`>=`,`>`.
**compare_operator** ?

2021-04-13 10:01 UTC, karolkielecki commented on docs/developer/available-plugins/admin-emails.mdx
> +Internally the plugin is familiar to [`UserEmails`](developer/available-plugins/user-emails.mdx), with a few notable differences:
```suggestion
Internally, the plugin is similar to [`UserEmails`](developer/available-plugins/user-emails.mdx), with a few notable differences:
```

2021-04-13 10:03 UTC, karolkielecki commented on docs/developer/extending/apps/creating-and-installing-apps-from-the-command-line.mdx
> +To create a local App with explicitly provided permissions use the `create_app` command.
```suggestion
To create a local App with explicitly provided permissions, use the `create_app` command.
```

2021-04-13 10:09 UTC, karolkielecki commented on docs/developer/extending/apps/creating-and-installing-apps-from-the-command-line.mdx
> +To install a `third-party` App based on its manifest URL use the `install_app` command.
```suggestion
To install a `third-party` App based on its manifest URL, use the `install_app` command.
```

2021-04-13 13:27 UTC, karolkielecki commented on docs/developer/api-reference/enums/webhook-event-type-enum.mdx
> +An order is confirmed (status change unconfirmed -> unfulfilled) by staff user using OrderConfirm mutation. Also triggers when user finish checkout and shop setting `automatically_confirm_all_new_ord
```suggestion
An order is confirmed (status change: unconfirmed -> unfulfilled) by a staff user using the OrderConfirm mutation. It also triggers when the user completes the checkout process and the shop setting `automatically_confirm_all_new_orders` is enabled.
```

2021-04-13 13:28 UTC, karolkielecki commented on docs/developer/api-reference/enums/webhook-event-type-enum.mdx
> +A checkout is updated. Also triggers for all updates related to a checkout.
```suggestion
A checkout is updated. It also triggers all updates related to the checkout process.
```

2021-04-14 08:14 UTC, karolkielecki requested changes

2021-04-14 08:14 UTC, karolkielecki commented on docs/developer/available-plugins/admin-emails.mdx
> +Internally the plugin is familiar to [`UserEmails`](developer/available-plugins/user-emails.mdx), with a few notable differences:
```suggestion
Internally, the plugin is similar to [`UserEmails`](developer/available-plugins/user-emails.mdx), with a few notable differences:
```

2021-04-14 08:14 UTC, karolkielecki commented on docs/developer/api-reference/enums/webhook-event-type-enum.mdx
> +A checkout is updated. Also triggers for all updates related to a checkout.
```suggestion
A checkout is updated. It also triggers all updates related to the checkout process.
```

2021-04-14 08:14 UTC, karolkielecki commented on docs/developer/api-reference/enums/webhook-event-type-enum.mdx
> +An order is confirmed (status change unconfirmed -> unfulfilled) by staff user using OrderConfirm mutation. Also triggers when user finish checkout and shop setting `automatically_confirm_all_new_ord
```suggestion
An order is confirmed (status change: unconfirmed -> unfulfilled) by a staff user using the OrderConfirm mutation. It also triggers when the user completes the checkout process and the shop setting `automatically_confirm_all_new_orders` is enabled.
```

2021-04-14 08:14 UTC, karolkielecki commented on docs/developer/extending/apps/creating-and-installing-apps-from-the-command-line.mdx
> +To create a local App with explicitly provided permissions use the `create_app` command.
```suggestion
To create a local App with explicitly provided permissions, use the `create_app` command.
```

2021-04-14 08:14 UTC, karolkielecki commented on docs/developer/extending/apps/creating-and-installing-apps-from-the-command-line.mdx
> +To install a `third-party` App based on its manifest URL use the `install_app` command.
```suggestion
To install a `third-party` App based on its manifest URL, use the `install_app` command.
```

2021-04-16 12:31 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/mirumee/saleor-docs?pullRequest=246) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/mirumee/saleor-docs?pullRequest=246) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: krzysztofwolski<br/>:x: korycins<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/mirumee/saleor-docs?pullRequest=246) it.</sub>

2021-04-19 10:57 UTC, merged