Clarify stock quantities query
mirumee/saleor-docs pull request #258
Opened 2021-04-22 13:33 UTC by krzysztofwolski

Based on developer feedback, I would like to clarify how quantities behave in API

2021-04-23 07:06 UTC, fowczarek approved these changes

2021-04-27 10:16 UTC, karolkielecki requested changes

2021-04-27 10:16 UTC, karolkielecki commented on docs/developer/products.mdx
> +To clarify difference between `quantityAvailable` and stocks, we will query both for the product variant:
```suggestion
To clarify the difference between `quantityAvailable` and stocks, we will query both for the product variant: 
```

2021-04-27 10:16 UTC, karolkielecki commented on docs/developer/products.mdx
> +Warehouse is chosen based on argument `address`. If argument is ommited, API will return highest available quantity.
```suggestion
A warehouse is chosen based on the argument `address`. If the argument is omitted, API will return the highest available quantity.
```

2021-04-27 11:58 UTC, merged