Add required permissions section to the checkouts
mirumee/saleor-docs pull request #264
Opened 2021-05-17 17:09 UTC by krzysztofwolski

2021-05-18 05:37 UTC, korycins approved these changes

2021-05-19 09:38 UTC, karolkielecki requested changes

2021-05-19 09:38 UTC, karolkielecki commented on docs/developer/checkout.mdx
> +If Checkout is assigned to the user, only this user and staff user with permission `MANAGE_CHECKOUTS` can query its data. Checkouts without assigned user can be queried modified using token, without
```suggestion
If the checkout permission is assigned to the user, only this user and staff users with permission `MANAGE_CHECKOUTS` can query its data. Checkouts without assigned users can be queried modified using the token without additional permissions.  
```

2021-05-19 09:47 UTC, karolkielecki approved these changes

2021-05-19 09:49 UTC, merged