Describe me query
mirumee/saleor-docs pull request #267
Opened 2021-05-21 13:15 UTC by krzysztofwolski

2021-05-21 13:15 UTC, patrys commented
Task linked: [SALEOR-3440 Describe me query in Users section](https://app.clickup.com/t/2549495/SALEOR-3440)

2021-05-21 13:24 UTC, korycins commented on docs/developer/users.mdx
> +If request is missing `authorization` header or, server will response with `null`.
`If request is missing authorization header or,`  Did you miss here something?

2021-05-21 13:26 UTC, krzysztofwolski commented on docs/developer/users.mdx
> +If request is missing `authorization` header or, server will response with `null`.
```suggestion
If the request is missing the `authorization` header or the token is invalid, the server will respond with `null`.
```

2021-05-24 08:19 UTC, korycins approved these changes

2021-05-24 09:11 UTC, patrys commented on docs/developer/users.mdx
> +## Accessing authorizated user info
```suggestion
## Accessing information about the authenticated user
```

"Authentication" is about your identity, "authorization" is about your privileges.

2021-05-24 10:35 UTC, karolkielecki requested changes

2021-05-24 10:35 UTC, karolkielecki commented on docs/developer/users.mdx
> +[`me`](developer/api-reference/queries/me.mdx) allow you to get information about currently logged in user.
```suggestion
The [`me`](developer/api-reference/queries/me.mdx) query allows you to get information about currently logged in user. 
```

2021-05-24 10:36 UTC, karolkielecki approved these changes

2021-05-24 11:02 UTC, merged